### ISSUE TITLE
provide dictionary of ontology terms

### ISSUE THREAD

**Issue by jgbaum** [jamesaoverton/covic-db-tool-prototype#1]
When Brendan's code builds the db from the git repo, he needs a way to map the ontology identifiers to labels.  We can work with the TSV files in this repo, but it's probably cleaner if this package provides a function that returns a dictionary of ontology ids mapping to their fields & values (i.e. dictionary of dictionaries).  For example:

`{ OBI:0000001 => { label => 'experiment, URI => 'https://ontology.com/OBI_0000001, ...} ... }`

What do you think, @jamesaoverton ?

**Comment by jamesaoverton** [comment]
[`config.py`](https://github.com/jamesaoverton/covic-db-tool-prototype/blob/master/src/covicdbtools/config.py) holds this information, which it loads from [`config.json`](https://github.com/jamesaoverton/covic-db-tool-prototype/blob/master/src/covicdbtools/config.json). Does that cover this requirement?

**Comment by jgbaum** [comment]
Maybe?  What do you think, @bha008?

**Comment by bha008** [comment]
@jamesaoverton perfect, I can work with that
