### ISSUE TITLE
Error parsing non string values

### ISSUE THREAD

**Issue by bha008** [jamesaoverton/covic-db-tool-prototype#2]
https://github.com/jamesaoverton/covic-db-tool-prototype/blob/master/src/covicdbtools/submissions.py#L79

Looks like this line is the culprit. 
[5 (2).xlsx](https://github.com/jamesaoverton/covic-db-tool-prototype/files/4839416/5.2.xlsx)

The attached file has a value of 10 for the 'n' column. It's not being cast to a string to use strip()

**Comment by jamesaoverton** [comment]
Thanks. Should be fixed by 95614892ede46d3f428bc17bbca09ce834cf9d87
