### ISSUE TITLE
COVIC ID validator accepting trailing strings

### ISSUE THREAD

**Issue by bha008** [jamesaoverton/covic-db-tool-prototype#3]
It looks like a submission got through the validator without throwing an error for invalid covic ID

```COVIC-6 (batch1)```

Should that be caught in the validator or handled by the web app?

**Comment by jamesaoverton** [comment]
I will check for it, and let you know when it's fixed.

**Comment by jamesaoverton** [comment]
This was fixed in 34459f867009bf63bab4b41f27b6fa33e811f0cd
